### ISSUE TITLE
Keyboard hook seems to induce some lag.

### ISSUE THREAD

**Issue by funkyspacecadet** [mzomparelli/zVirtualDesktop#100]
Hi,

I just discovered this app and it's amazing!

There appears to be an issue with enabling keyboard hook.
I don't use mouse hook as it renders the mouse too unresponsive for me.

Symptoms: When enabled, some tasks in apps that require drag & drop/ dragging items around, when a modifier key is held down becomes slower/less responsive, such as in Inkscape, Firefox etc

I also use Autohotkey as I use that to send some hotkeys to Windows magnifier + launch programs but even with Autohotkey completely disabled I still experience some lag with keyboard hook enabled.

If I enable my Auothotkey script again with ZVD running, if I use my Auotohotkey binding to use the magnifier (Win+Mousewheel Up/Down) then sometimes the Start menu is triggered, but if I close ZVD the problem resolves.  I assume in thise case it might be a conflict, but since I'm having some lag with running ZVD only I figured it might be a bug.

Specs:
Lenovo Thinkpad T520
Core i7-2670QM, 8GB RAM, Intel SSD, Win10 2016 LTSB x64

**Comment by mzomparelli** [comment]
First off, thanks for trying zVD. I'm glad you like it.

The issue for you is still the mouse hook. The keyboard hook won't really cause problems because there simply isn't enough events for it to cause a bottle neck. The mouse hook triggers an event every time the mouse moves so you can see this would equate to a lot of events. When you turn off the mouse hook in the settings window it will still turn on automatically when you are pressing a modifier key and will turn off when no modifiers are pressed. I will add the ability to turn off the mouse hook completely.

There is a known bug in zVD for the Windows key. Certain hotkeys that use the WIN key may make the Start Menu pop up. I'm still looking into this issue. Your mouse scroll hotkey is AHK though so it really shouldn't be happening in your case.

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow Permanent Mouse Hook Disable](https://trello.com/c/w4Se14Jy/10-allow-permanent-mouse-hook-disable)

**Comment by mzomparelli** [comment]
If it's not asking too much and you really like zVD and the support that I provide for zVD them please consider starring the app on GitHub and donating. All donations are greatly appreciated.

I'm trying to get enough stars to get on the GitHub trending list so that more people see it.

**Comment by jjhidalgar** [comment]
I will use this issue to tell my problems with the keyboard hook.

The thing is that my example is kindof funny because it happens inside a game (league of legends).

I currently have version 1.0.67 with keyboard hooks enabled and mouse hooks disabled.

Whenever inside the game, I press ALT (or CTRL too) and then DRAG, while dragging the mouse sensibility becomes incredibly high, so high that even the shortest move will take the mouse out of the screen, as seen in this screenshot: https://i.imgur.com/7vG1LbV.png

That happens even if my unique zVirtualDesktop  shortcut is set on windows+shift key, leaving ALT totally unused. Even disabling every single ALT shortcut that was set by default.

The only way to fix this is by disabling the keyboard hooks or by closing the app totally.

It might have something to do with apps/games that also use keyboard hooks.

**Comment by mzomparelli** [comment]
The issue is not the keyboard hook. When you turn off the mouse hook it will still come on when pressing a modifier key and the symptoms you describe are the result of the mouse hook. In version 1.0.68 you will be able to turn off the mouse hook completely.

**Comment by jjhidalgar** [comment]
Awesome.

**Comment by mzomparelli** [comment]
I understand how frustrating the mouse lag can be so I went in and removed the code that starts the hook when a modifier is pressed and published this as a new 1.0.67. I might add an option to turn it on with modifier in the future. I'm confident this will resolve your the lag issues. If you are still experiencing issues let me know.

https://zomp.co/files.aspx?id=zvd

**Comment by jjhidalgar** [comment]
It works :P

**Comment by loumizhu** [comment]
Hi
I searched the issues before reporting mine, and it seemed similar to this, that's why I'm adding a comment to this old discussion (so let me know if it should be a new issue)
The zVirtualDesktop works great by itself.
But as a user of autohotkey I also experienced some issues.
Send keys with autohotkey became very laggy when running zVirtualDesktop.
Not necessarily sending hotkeys with modifiers, but even sending letter or arrow keys by themselves ...
Some of my scripts use mouse tracking, and have become slower.

I'm not complaining , just reporting this.
zVirtualDesktop seems to slow down the execution of my AutoHotkey scripts.

thanks for your time
