### ISSUE TITLE
Request: Hotkey action: Switch to previous desktop

### ISSUE THREAD

**Issue by nicolasdejong** [mzomparelli/zVirtualDesktop#115]
Sometimes it is convenient to switch between the current and previously selected desktop (e.g. desktop 1 with the mail app and desktop 5 with the work, or desktop 4 with client work and desktop 6 with server work). Having the option to switch between them with a single key press would be nice.

It is similar to the ctrl-tab to toggle between the two recently selected tabs in most editors and (some) browsers.

**Comment by mzomparelli** [comment]
I've been thinking of this exact idea. If I do this then I need to rename how I currently use Next and Previous since I am using them incorrectly. Doing this would cause all of you to have to recreate those hotkeys. If I renamed Next and Previous what do you think a good term for those is? Maybe just Left and Right?

**Comment by nicolasdejong** [comment]
Perhaps "Navigate to desktop +1" /-1/+3/-3 can be used instead? Left and right is also possible, but I find +1 sounding more precise. But that may be professional deformation :-) No strong opinion on this one.

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hotkey Action: Switch to Previous Desktop](https://trello.com/c/u48pRKQQ/39-hotkey-action-switch-to-previous-desktop)

**Comment by mzomparelli** [comment]
Sorry I haven't gotten this done yet. Here's what I'm going to do...

I'm going to release a new version that converts the current "Next" and "Previous" actions to "Plus 1" and "Minus 1" to match the "Plus 3" and "Minus 3"

Then I'm going to wait a two weeks for everyone to update. Lastly, I'll release an update that brings back "Previous" to function as this issue specifies.

**Comment by mzomparelli** [comment]
Or maybe since I'm lazy I'll just call it "Previous Active Desktop". Would that be ok with you? I know it's not great, but it'll work.

**Comment by nicolasdejong** [comment]
That's ok by me. It describes the action well enough. Having this extra key option is great!

**Comment by mzomparelli** [comment]
I just published 1.0.80.5

Upon starting up zVD, the previous active desktop will be set to desktop 1. Once you start switching desktops it will track properly.

I've added the ability to Move Windows to the previous active desktop too.

Check it out and let me know if you have any issues. I'm marking as resolved because it appears to be working ok for me.

**Comment by nicolasdejong** [comment]
Works great! Love it! Thanks!

**Comment by mzomparelli** [comment]
I'm really liking this feature too. I setup CAPSLOCK+TAB to switch to the previous active desktop. Of course, this hotkey requires that you tick the box in settings that converts CAPSLOCK to a modifier key.
