### ISSUE TITLE
Boring grey

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#118]
Hi, looking at this image https://i.imgur.com/I3LvK2d.jpg, I wonder ; Why is it that two programs comes up as grey boxes?
The leftmost is an ordinary Excel sheet, and the one next to it is the MS Mail inbox.
Is it coincidental that they are both MS-apps?

**Comment by mzomparelli** [comment]
The mail app will do this as will all UWP apps. Those are apps from the Microsoft Store. Is your version of Excel the store app or the desktop app?

I’m working on the solution to display thumbnails for UWP apps.

**Comment by oywino** [comment]
Great :)
What is UWP by the way?
My Excel is the one included in the Office 16 package.

**Comment by mzomparelli** [comment]
UWP = Universal Windows Platform. These are the apps you download from the Microsoft Store. You Excel window should not be displaying grey. I'll be looking into this..

**Comment by mzomparelli** [comment]
I meant to mention this in the last comment, but I was rushing to leave work. For Excel having the gray thumbnail, that might get resolved with a PC reboot. I had some thumbnails to the same thing after I updated to the Fall creators update (1709) and rebooting fixed that.

**Comment by mzomparelli** [comment]
I just noticed a zVD review in Word on your screenshot. Are you writing that review? I would love to read it.

**Comment by mzomparelli** [comment]
The issue with the UWP apps is tricky.

When on the same desktop as the UWP app, I only see a FrameHost (C:\Windows\System32\ApplicationFrameHost.exe) window handle.

When not on the same desktop as the UWP app I see the FrameHost handle and I also see the handle that points to the UWP app's location. The latter displays the thumbnail properly.

For some reason, I cannot get the handle of the actual UWP app while on the same desktop. However, I was able to adjust the code so that when on a different desktop than the UWP app it will only display one thumbnail and it will be the real thumbnail. Unfortunately, when on the same desktop as the UWP, I cannot get the actual thumbnail so the gray one appears.

I'm still working on this.

**Comment by mzomparelli** [comment]
I think I solved this the best I can for now. I'll keep it on the back burner.

**Comment by mzomparelli** [comment]
Reopening this....I'm not sure why I closed it in the first place.

I've made some progress with displaying thumbnails for WPF and UWP apps. Now you will get a thumbnail when you are on the same desktop as the window or the window is pinned. I'm still trying to get the thumbnail when the window is on another desktop.

This is clearly something to do with WinForms and testing my code from a WPF application works fine. Because of that, I am also considering redoing DesktopView as a WPF window. That will take some time to complete and I will look for a WinForms solution in the meantime.

**Comment by mzomparelli** [comment]
This is now resolved. You will get thumbnails for all UWP and WPF windows now.
Z-order is messing up because the parent window has the correct z-order, but the window with the thumbnail does not have a z-order. I'm trying to work out a solution to use the parent z-order in place.

**Comment by mzomparelli** [comment]
Since thumbnails are displaying now I am going to close this issue. I will open up more issues to deal with the issues that my hack has caused.

**Comment by mzomparelli** [comment]
The z-order issue has been resolved as well.

**Comment by oywino** [comment]
Great!  😄  (But what version has these fixes?)

**Comment by mzomparelli** [comment]
Do a force update to get the current build of 1.0.82.0. Let me know if you are still seeing the boring grey.

**Comment by mzomparelli** [comment]
I just pushed out 1.0.82.1. A certain window type was being excluded from DesktopView.
