### ISSUE TITLE
Licence Change of Nov 9th, personal use on corporate system no longer possible

### ISSUE THREAD

**Issue by rwalatalo** [mzomparelli/zVirtualDesktop#153]
The license change means it's no longer possible for an individual who is not in a position to represent the corporation who employees them to use this software.  Prior to the change this could be claimed as personal use, with this change it can not, additionally as any 'corporate' use needs to be done at the corporate level there is no option for individual use outside of some corporate license.  

Prior to this change, there only definition of corporate use was distribution:
...
...
USE:
Permission is hereby granted, free of charge, to any person obtaining a copy
of this Software and associated documentation files (the "Software"), to use the 
Software for personal use only. Commercial users must have my approval before 
distributing the Software throughout an organization.
...
...

While I believed the old license did allow personal use on corporate systems, the new license makes this clear that it's no longer allowed.      I suspect a large number of users are given flexibility to personally install applications on a corporate access as long as they abide by the application's licensing requirements.  

In light of this license change, I have no choice but to discontinue use and uninstall this software as I can no longer met the requirements of the new license.  If you did not intend to prohibit individuals from using this software via personal choice you should modify your license.

**Comment by mzomparelli** [comment]
I am working on a new license.

At this point, version 1.0.71 and up, can be used on any machine so long as it is registered. Even the trial can be used on any machine for 10 days. Purchasing a license gives you the freedom to use zVirtualDesktop on any machine whether it be personally owned or owned by an organization.

The license you are reading was in place during the beta trial. What version is that? You should upgrade and purchase a license so that you may use on any computer. Purchasing helps me a lot. I put a lot of work into this program. I also have personal issues going on which require money.

I use this application every day more than I use any other and it adds significant value to my productivity. Because of that, I would have purchased this program from whomever was selling it. If you don't think the program is worth anything then feel free to not use it.
