### ISSUE TITLE
Trial period expried on first-run

### ISSUE THREAD

**Issue by adamvoss** [mzomparelli/zVirtualDesktop#156]
Downloaded from the README.md link to check this out.  On first run it pops up a message saying the trial has expired even though I have never loaded the application before.

**Comment by mzomparelli** [comment]
Is that the only message you see?

Using the app with the link below, please let me know what it shows you in the text box. This app gets your  hardware ID. I suspect there is an issue getting this value on your machine. 

If this textbox is empty then you can tell me that here in this issue otherwise please don't post your hardware ID here. Instead send it to me via email at zVirtualDesktop@gmail.com.


https://zomp.co/Files.aspx?id=zVD_Hardware

**Comment by mzomparelli** [comment]
@adamvoss Is this still an issue for you?
