### ISSUE TITLE
Shortcut jump fails sometimes

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#17]
I'm on v1.6
I'm on Desktop 1 and I have Another App (VNC Viewer) running on Desktop 4.
All running apps also appear on my taskbar.
I could hit Ctrl-Win-4 to go to desktop 4 where I know VNC Viewer is running, but even faster is just to click the VNC Viewer taskbar icon (especially if I do not recall exactly which desktop it is currently using). Then Windows jumps to desktop 4 right away.
However, zVD fails to pick up the fact that I have changed desktop, on certain apps, and zVD becomes completely unresponsive to any further Ctrl-Win-n attempts. 
I first have to click the mouse somewhere on desktop 4 to make zVD aware of my whereabouts. Then it becomes responsive again.
This bug is only related to some Apps. What exactly causes this, I don't know. But I suspect it may have something to do with apps relying on a virtual mouse emulation (typically remote desktop apps).

**Comment by mzomparelli** [comment]
@oywino Thanks for pointing out this bug. I will try to reproduce it so that I can fix it.

**Comment by mzomparelli** [comment]
@oywino Are you saying that when this happens that even the system tray icon does not tell you that you are on desktop 4? I've tested this it appears that the keyboard and mouse are going to the remote computer. This actually makes sense. If I was using a remote PC I would like to be able to use hotkeys on that remote PC instead of it triggering the hotkeys for the client PC. If this only happens with apps that allow you to remotely or virtually use another machine then I don't see a fix happening because it should be working this way for these windows. Do you agree?

**Comment by oywino** [comment]
No, the number in the Tray Icon is correct. So I guess you are right. Sorry for bringing it up.

**Comment by mzomparelli** [comment]
No problem. Don't hesitate bringing anything up. And certainly don't be sorry for bringing it up.
