### ISSUE TITLE
Round Robin

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#18]
Hi, I was under the impression that when I use Ctrl-Win-RightArrow and reach the last Desktop, it would roll over to the beginning again.... ? (And vice versa)

**Comment by mzomparelli** [comment]
Remember, CTRL+WIN+Arrow is a Windows default. I can try overriding the default.

**Comment by mzomparelli** [comment]
Also, thanks a lot for the donation. That means a lot to me and I really appreciate it.

**Comment by mzomparelli** [comment]
Sorry, my day job kicked my ass today and I ended up bringing work home with me. I'll look into this as soon as I can.

**Comment by mzomparelli** [comment]
I set the code up to round robin like you want. You can create your own hotkeys for next and previous and it should work like you expect. I'm still considering overriding the default ones.

I haven't tested it. I'm hoping you do that and provide feedback.

https://github.com/mzomparelli/zVirtualDesktop/blob/master/zVirtualDesktop/bin/Release/zVirtualDesktop.zip?raw=true

**Comment by mzomparelli** [comment]
Actually, the above is true for moving windows and following, but not true for navigation. For that I need to redesign it a little bit.

**Comment by mzomparelli** [comment]
I'm still working on overriding the default windows hotkeys. I'm still not sure it is worth a round robin effect.

**Comment by mzomparelli** [comment]
@oywino , I've been successful in overriding the CTRL+WIN+Arrow with my own implementation. The problem is, with this method you can't create a standard hotkey for it because this method overrides all hotkeys that I choose. I might switch my hotkeys to use this method. What this means is that if you create a 'hotkey' in my app then it would override any hotkey already there without warning. This is good in that you can choose any hotkey that you want, but it's bad that you don't get a warning that it's in use. I'd like your opinion if you don't mind.

**Comment by mzomparelli** [comment]
v1.0.23 - I added a check box on the hotkey tab that allows you to override the default windows hotkeys for this action. If you check this box then you will get the round robin effect you like when navigating the desktops with the arrow keys.
