### ISSUE TITLE
Strange behavior when using Win+NumPadX to navigate

### ISSUE THREAD

**Issue by mnsh** [mzomparelli/zVirtualDesktop#187]
Using the following hotkey setup:
```
Navigate to Desktop #1 - WIN+NumPad1
Navigate to Desktop #2 - WIN+NumPad2
Navigate to Desktop #3 - WIN+NumPad3
...
Navigate to Desktop #9 - WIN+NumPad9
```
Each desktop change is followed by an extra keyboard event (`Ctrl-Esc` or `Esc`) sent to whichever app is in focus. This happens right after the first key is released (doesn't matter whether NumPadX or Win is released first).

The issue seems specific to using only `Win` as a modifier; if I add the following:
```
Navigate to Desktop #1 - ALT+CTRL+NumPad1
Navigate to Desktop #1 - CTRL+WIN+NumPad1
```
then using those to switch to desktop 1 does not result in any extra keypresses.

Version 1.0.84.1 on win10 1803.

**Comment by mzomparelli** [comment]
Yes, this is specific to the Win key and I do it for a reason. What issue is it causing for you when CTRL+ESC gets sent to a window? CTRL+ESC is the windows default hotkey to open the start menu. It's like pressing the Win key. While I have a reason for doing this, I'd like to know what issue it is causing you before I look into changing it. This will only happen when you use the WIN key as the only modifier in your hotkey. This means you can avoid the issue by adding another modifier.

**Comment by mzomparelli** [comment]
The reason I do this is that the start menu liked to pop-up when using hotkeys that only used WIN modifier. This solved the issue and didn't cause any issues with windows I have open. This is why I'm trying to understand what issue it's causing on your machine. Maybe it's a specific window causing an issue with these key presses?

**Comment by mnsh** [comment]
Many apps, including any webapp will end up treating Ctrl+Esc as just Esc, causing all kinds of annoyances. Long running process with a cancel button? Bam, interrupted. A lot of app windows (say, SomeApp -> Settings -> Advanced) will just close, cancelling any changes you have made.

In bash (in a putty or git bash), Ctrl-Esc results in the next key you press being ignored, opening up for a whole universe of funny and/or tragic mishaps - say you looked something up on another desktop and switch back to finish an `rm -f  ` with `a*` and end up running `rm -f *` instead.

20+ years of Win+NumPadX makes the switch to another set of hotkeys a huge inconvenience. I'd rather not =)

**Comment by mzomparelli** [comment]
Thanks for the info, I had no idea that some programs would pick that up as just the ESC key. In my opinion that's incorrect behavior by those web apps because it wasn't the escape key that was sent. It always is CTRL+ESC which is different. Shame on those web apps for ignoring the CTRL key.

I'm looking at the code now to see how I can handle this differently.

**Comment by mzomparelli** [comment]
I have a solution for this that I will implement this evening or sooner. I’d like you to test it out when I do. Stay tuned and thanks for the feedback.

**Comment by mzomparelli** [comment]
I just published 1.0.84.2 in an effort to correct the issue you described. Please test it out and let me know if the issue persists. I still need to ensure this fix isn't interfering with anything else.

**Comment by mnsh** [comment]
Trying out 1.0.84.2 - so far, it seems to fix my problem.

**Comment by mzomparelli** [comment]
That's great to hear. It is in fact conflicting with something else, but I'll figure it out.

**Comment by mzomparelli** [comment]
I've corrected the conflict and I'm publishing now.

**Comment by mnsh** [comment]
Don't know if it's related, but: 1.0.84.3 fixes an issue I noticed with 1.0.84.2, where switching to desktop 1 (and only desktop 1) always failed to restore focus to the last focused window. Cool.

**Comment by mzomparelli** [comment]
That was the conflict :)

**Comment by mzomparelli** [comment]
Instead of using the Win32 API `RegisterHotkey` I chose to implement my own hotkey manager using a keyboard hook and mouse hook. This meant that I needed to handle KeyUp and KeyDown for your entire machine which is a lot more difficult than just calling a Win32 API function, but the ability for me to get down to key presses makes it worth the added complexity. So far it has been working great, but I miss stuff and rely on users like you to inform me on the things I mess up. 

So for that I thank you. You've made zVirtualDesktop better :)
