### ISSUE TITLE
Issues after latest upgrade

### ISSUE THREAD

**Issue by jdmcfadden-usx** [mzomparelli/zVirtualDesktop#196]
Upgraded to 1.0.86.0 and I'm having a several issues. 

First: The Alt-Win-Arrow key keyboard hooks that move windows to the next desktop appear to have stopped working. I've tried both toggling the hooks off and on in the settings and stopping and restarting the app and rebooting the computer. Nothing helps.

Second: Originally, I would Win-Tab and see only a couple of desktops. Then I used Alt-Win-7 to go to desktop 7 and now I can Win-Tab and see seven desktops.

Third: Most of my pinned apps have come unpinned.

**Comment by mzomparelli** [comment]
1.) The ALT-WIN-Arrow Key has been removed as a default. Originally, it was a check box to override the windows hotkeys to allow "Round Robin". This has been removed, but you can accomplish the same thing by creating the hotkeys manually.

2.) This still works. I just tested. Maybe I'm misunderstanding your issue here.

3.) Are you having an issue re-pinning them? By default, Windows removes pins upon reboot.
