### ISSUE TITLE
Naming more than 9 desktop?

### ISSUE THREAD

**Issue by SebSysAdminSuly** [mzomparelli/zVirtualDesktop#233]

**Comment by SebSysAdminSuly** [comment]
It's that possible to add the feature of naming more than 9 desktop? 

I currently searching for an application to manage up to 15 virtual desktop. 

The reason for more than 9 is for special case in a call center. User have too much windows so we want a way to seperate them efficiently and when they receive a call from a particular customer I pop the right virtual desktop. 

Thanks.

**Comment by mzomparelli** [comment]
While you can't name more than 9 desktops within the settings form, you can name as many as you'd like using DesktopView. I hope this helps. I might make the settings form allow for more, but that would probably require a different way than I am currently doing.

**Comment by mzomparelli** [comment]
You can access DesktopView by left clicking the the tray icon or using Win+Tab

**Comment by SebSysAdminSuly** [comment]
Thanks for reply.

**Comment by mzomparelli** [comment]
No problem. I'm happy to help and I'm happy you are trying to make use of zVD. I know it's not perfect and I still want to get back in and fix some quarks, I believe it functions well enough. I use it everyday and I get annoyed easily. So when I get annoyed on something you can count on my looking for a fix. If something about zVD annoys you, feel free to tell me about it.

**Comment by SebSysAdminSuly** [comment]
Is there a way to create a config of an export it to another computer? 

So example, everytime zVirtualDesktop is launch it creates the same X desktop with Y name. Be able to export this config to another computer. 

After playing with it for an hour it seems I could do everything I want expect I would have to setup everything by hand on each computer.

**Comment by mzomparelli** [comment]
So you can't create a config to create desktops (at least not with zVD currently, although a Powershell could now), however, the names of each desktop are stored in the settings file. It is possible to copy the settings file to another computer and it would then have the same configuration on both computers.

**Comment by SebSysAdminSuly** [comment]
I naively tried to copy the .bin file in the %AppData% folder but on another computer but it didn't work and see if I get the settings. I will see again if I screw up somewhere. 

I know there's a powershell module to handle the virtualdesktop I played a bit with it. That defeat a bit the purpose of getting a tool like yours since I was looking into throwing money instead of time. 

I would see if I could use a combination of your tool and the powershell module for that. 

Quick last question if you answer to that reply, is your code is still public? Maybe I could add/adjust it to my case if still public. 

Otherwise your tool is very cool and Thank you very much for the quick answer.

**Comment by mzomparelli** [comment]
The final public fork can be found here.
https://github.com/jan-glx/zVirtualDesktop

I decided to close it mainly in order to make a little bit of cash. After seeing the PeachApp being sold for $10 and having a basic functionality. I feel like zVD adds a lot of useful functionality and the PeachApp simply falls short for being commercial software.

Another reason I decided to close it though is that I changed from using WinAPI Register Hotkey to a mouse/keyboard hook approach to hotkeys. This change allowed me to override Windows default and allows the CapsLock to be used as a modifier key. My fear with this was that a malicious person could fork a copy of zVD and turn it into a keylogger. The user would get great virtual desktop functionality while unknowingly having their key strokes logged. Not only is this very bad for the user, it also could disgrace the real zVD which is a trustworthy app. Not all users want to look at code. Some just want to run it and obtain the functionality.

In addition to the hotkey implementation change, the final public code does not contain DesktopVIew. 

It is still possible and very likely that zVD will become open source again. I can't say when, but it'll be when I get tired of maintaining the activation server and bug fixes. At which point I would publish one last build to my users that is unlocked and a message to tell them to go get the code. I would also warn them of the keylogging potential and to only run builds from trusted developers.

I would like to mention that your support is greatly appreciated. I worked hard on this to make it what it is. At the time that I converted to commercial I created this issue to speak to my users about my choice to do so.

https://github.com/mzomparelli/zVirtualDesktop/issues/142

**Comment by SebSysAdminSuly** [comment]
If I asked about the code it was not to steal it. I was a bit afraid that it could interpret it that way. 

I was planning to use dexpot atthe beginning. They offers all the feature, like they have a SDK with their implementation which was really interesting since I could wrap up all their work and integrate it in something more suited to my case, but I can't spend 1-2k$ on something that isn't updated anymore with the mess that is Windows 10. 

Since yours is using the native implementation of virtual desktop it is a bit safer and you seems to be really active. 

If with powershell i can make it work like I need I would be glad to make the company I work for support you :) 

I was planning to use the powershell script available on github to make it, but I would have to spend at least 10-20 hours to have something workable and support it. So I can understand what you mean.

**Comment by mzomparelli** [comment]
I certainly didn't mean to imply that I think you would steal it. However, once code is out there it's up for grabs. It would be much harder to justify charging people if someone has a fork of a free one that is the same version. I'm not saying you'd be the one doing that fork, but likely someone would be.

As far as an SDK. I would like to talk about that more and what your ideas are on how you'd like it to work. For instance, I have been considering allowing arguments to be passed in when executing zVD that could allow interaction with a running instance. Do you have any thoughts on that?

**Comment by SebSysAdminSuly** [comment]
Well in a ideal world if we could do all the interaction possible from the UI within a SDK or with commandline it would be perfect. 

Personally this is what I'm looking for : 

-  Possibility to create a profile and export it so it's easier if you have 20 desktop to deploy the same config. (I have to test again if that one is working)
- Possibility to change desktop from command line/SDK. Hotkeys are ok for power user, but in my case I fear that it would be too much for them to handle. I was thinking about creating an APP that let them manage this from an UI, but I have to do it by sending key it sometimes failed if the user touch something. 
- If I can't create a basic profile, I would like to be able to recreate it with a script. 
- Ability to run a script on the first startup of a particular desktop 
- Ability to give name to virtual desktop with SDK
- ability to launch a program in a particular virtual desktop. For myself It's fine I can do it from UI, but in my case it's useless if i can't do programmatically. 

This is just an example, but that's what I'm looking for : 

zVirtualDesktop.exe -StartVDesktop "8" (start 8 virtualdesktop)
zVirtualDesktop.exe -SwitchDesktop "1" (switch to desktop 1)
zVirtualDesktop.exe -LablVDesktop "1" -Name "Customer 1" (assign label to virtualdesktop)
zVirtualDesktop.exe -StartProcess "Program" -vDesktop "5" (start a program and pin the program to a particuliar desktop)
zVirtualDesktop.exe -ShowAllCurrentVDesktop (Equivalent of Windows key + tab)
zVirtualDesktop.exe -ListVDesktopProperties (list virual desktop with their current programs, label, ID, etc)

**Comment by mzomparelli** [comment]
Thank you for this. It looks likes all of the command line functionality you specify should be pretty doable and is aligned with what I was already thinking. I'm probably going to take your last post and create a new issue out of it. I love the ideas. I just need to buckle down and do it.
