### ISSUE TITLE
Trial period internet missing message despite existing registration

### ISSUE THREAD

**Issue by DrGierth** [mzomparelli/zVirtualDesktop#254]
Error Message:
![grafik](https://user-images.githubusercontent.com/12048733/74174347-10145600-4c34-11ea-8f68-2ce92ac71cd0.png)
Account details:
![grafik](https://user-images.githubusercontent.com/12048733/74174663-99c42380-4c34-11ea-9adc-2d7de051cb45.png)

Hello Mr. Zomparelli,

I get the trial period internet connection neccessary message, despite I have an account and the registered computer is the right computer. I cannot reregister because of a ten day  period:
![grafik](https://user-images.githubusercontent.com/12048733/74175099-6d5cd700-4c35-11ea-8424-8c61ac679ea1.png)

What can I do?

Thank you in advance for your efforts.

Dr. Michael Gierth

**Comment by mzomparelli** [comment]
I'm sorry for that. I removed your registered computer which will allow you to register again. This could be due to a fresh Windows install or a Windows update. I am looking into this. The fix might mean you will have to re-register yet again. Let me know if you continue to have this issue after registering again.

**Comment by DrGierth** [comment]
Hello Mr. Zomparelli,

when I register the computer I get an error " a file was not  found" an the following Account screen:

![grafik](https://user-images.githubusercontent.com/12048733/74245768-d3a03300-4ce3-11ea-9d1f-6a34dc1fdf12.png)

When I retry to register I get:
![grafik](https://user-images.githubusercontent.com/12048733/74245640-99cf2c80-4ce3-11ea-893e-589334be8d38.png)

It remains difficult.

Regards 

Michael

**Comment by DrGierth** [comment]
I made a Forced Update an then it was OK!

Regards 

Michael

**Comment by mzomparelli** [comment]
I forgot to move my private key to the new server which prevented the creation of the local license generation. This is what it meant by file not found. I'm really sorry for that. This is fixed now and you should be able to register.

**Comment by mzomparelli** [comment]
Also, I'm pretty sure your issue was a recent update to Windows 10. I'm going to make some changes to account for that, but I will wait more than 10 days you'll b e able to unregister and register again. The changes will affect licensing so registering again will be mandatory once I make this change.

**Comment by mzomparelli** [comment]
I have published a new version that should eliminate any issues with licensing and Windows updates. Once you download this version you will have to register your computer again. There is no need for you to do this now. You should wait until you are able to free your current license first. However, if you need me to free it again just let me know.

Again, I'm very sorry for the inconveniences this has caused.
