### ISSUE TITLE
offline activation

### ISSUE THREAD

**Issue by dsp0105** [mzomparelli/zVirtualDesktop#269]
Do you have the option of license file so that I can activate it offline?

**Comment by mzomparelli** [comment]
The offline license is downloaded when you register the computer. It will still check with the server on each startup. This check should only be mandatory for trial users. If you have a local license then you should be good to disconnect from the internet. The local license is transparent to you and stored in the settings file. Let me know if you have further issues.

**Comment by mzomparelli** [comment]
If the computer never has internet then we’ll need to figure something out for you.

**Comment by dsp0105** [comment]
unfortunately, it does not have internet at all.

**Comment by mzomparelli** [comment]
I'll be honest. I did think about this when I was creating the licensing mechanism, but I decided that majority of computers are connected to the internet these days. This creates a complex issue that I need to think about how to handle while maintaining the integrity of my licensing solution.

**Comment by dsp0105** [comment]
I have used other softwares which have offline activation such as SourceInsight, they send a license file when requested.

**Comment by dsp0105** [comment]
Hi michael, any update on this please?

**Comment by mzomparelli** [comment]
I'm really sorry for the delay on this. This is the next thing being released, but it requires getting the license management into the website. I'm making progress there as I have completed the log on and logoff. I just need to do a few more things to the site and make a few adjustments in zVD to make offline activation work.

**Comment by dsp0105** [comment]
thanks Michael for working on this.

I see a new version xxxx.8 is available, checking if offline activation is implemented?

**Comment by mzomparelli** [comment]
Not yet, sorry. Progress is being made though

**Comment by mzomparelli** [comment]
To lessen my risk on pirating, I need to be extremely careful how I do the offline activation because once I compile a version with this then there is no going back.

**Comment by dsp0105** [comment]
Cant you do something like mailing the license file to registered email address, once an user requests for a license file?

I see other software do like that.

**Comment by mzomparelli** [comment]
Yeah I see software that does that. I'm not sure how that works when it comes time for deactivation. Offline activation is easy. It's the offline deactivation that is trickier. The way I'm designing this, to activate, you will tell the zVD app that you want offline activation and it will provide you a string of text. You will need to exchange that string on my website for a license string and enter the license string into zVD. Offline deactivation will work similarly. You will tell zVD that you want to offline deactivate and it will immediately deactivate on that machine, but in order to free the license you will have to provide the string zVD returns to my website.

**Comment by mzomparelli** [comment]
I think I have enough to get your license activated offline, but it's manual right now. You have to email me the string zVD gives you so that I can create a license string and I will email the license back to you.

Since this is not finalized yet, I'm only going to provide you with this version so that you can activate offline. Please send me an email to zVirtualDesktop@gmail.com and specify the version of Windows 10 you are running.

**Comment by dsp0105** [comment]
Great! thanks Michael, I will mail you.

**Comment by dsp0105** [comment]
I have sent an email as you suggested to zVirtualDEsktop@gmail.com 
I have tried to install the trial software (for win 1809) on my offline computer and saw a crash.
Hopefully it is taken care in the custom version you are going to send me,.

**Comment by mzomparelli** [comment]
Let me know if there is still an issue. I'm leaving this issue open until I have finalized the offline activation.

**Comment by mzomparelli** [comment]
Offline activation is now available in 1.0.96.0
