### ISSUE TITLE
zVirtualDesktop will not launch

### ISSUE THREAD

**Issue by J-MaFf** [mzomparelli/zVirtualDesktop#276]
I just reinstalled windows as part of a pc clean, and I went to install zVirtualDesktop. I recently purchased a license and I am loving the program. The only problem Is that I cannot for the life of me get the program to launch. I have tried so much. Ran as an administrator, tried all windows versions, and even attempted to install via chocolatey. If I spam the shortcut it will give me a message saying "zVirtualDesktop is already running, please wait etc". It never shows up in the task manager or the taskbar. I could use some insight. Thank you,

Joey

**Comment by mzomparelli** [comment]
Sorry to hear about the issue. At least one other user had a similar issue. We fixed it with a custom build that removed some features that help protect my intellectual property. Let me review that and I'll probably push out new builds shortly.

**Comment by J-MaFf** [comment]
Thanks for the quick response! glad to hear that. Hopefully, it will work. This software has increased my productivity on my triple monitor setup immensely.

**Comment by mzomparelli** [comment]
I really appreciate the nice comments. It never gets old.

I just published new build, however I did not change the version number at all. Download from my site and let me know if the issue still persists.

https://zvirtualdesktop.com/

**Comment by mzomparelli** [comment]
Do you need me to remove this for you so you can register the new one? It's not going to allow you until it has been registered for 10 days.

![image](https://user-images.githubusercontent.com/10564234/106186069-588c9280-6169-11eb-861a-912eec9958a7.png)

**Comment by J-MaFf** [comment]
You're amazing! Im currently studying at university (computer science) and I want to be a software developer. You literally sqished a program-breaking bug in about 20 minutes. Kudos, lol. I would appreciate if you removed that registration as well :)

Keep up the amazing work!

Joey

**Comment by mzomparelli** [comment]
Your license is now free to use on another computer.

Thanks, it actually was less than 20 min. Probably a total of 8 minutes, but like I said, I already had an idea of what the problem was and solved a few week ago for one user. That actually took time to figure out. I had to have him share his screen and try multiple builds to identify the issue.

You got me beat with education. I'm a high school dropout :( I've taught myself a lot over the years, not only computer related stuff. Education is great, but you need to have passion for what you do as well. Also, coming up with ideas is difficult. zVD came naturally.  Win10 VD left a lot to be desired.

**Comment by J-MaFf** [comment]
I agree passion is definitely the most important part. Tbh I feel like I self teach myself things anyways as were doing "online classes" because of covid. Mostly in school for the credentialing :P Thanks again man, keep being a great developer  👍 

Joey
