### ISSUE TITLE
Application never starts on Win10 21H1

### ISSUE THREAD

**Issue by kimesbenjorgensen** [mzomparelli/zVirtualDesktop#278]
Debug collected from "Problem Reports". Also Windows Defender does not like the app is not signed.

Source
zVirtualDesktop

Summary
Stopped working

Date
‎19/‎02/‎2021 09:15

Status
Report sent

Description
Faulting Application Path:	C:\Users\kej_9\Downloads\zVirtualDesktop (2).exe

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	zVirtualDesktop (2).exe
Problem Signature 02:	1.0.96.3
Problem Signature 03:	60297ef6
Problem Signature 04:	zVirtualDesktop
Problem Signature 05:	1.0.96.3
Problem Signature 06:	60297ef6
Problem Signature 07:	2be
Problem Signature 08:	19
Problem Signature 09:	System.NotSupportedException
OS Version:	10.0.19043.2.0.0.256.48
Locale ID:	2057
Additional Information 1:	2beb
Additional Information 2:	2beba6fb4680d73a8c78ca7c24ccdb46
Additional Information 3:	078b
Additional Information 4:	078b0a27cefed7847512e263dc12b78f

Extra information about the problem
Bucket ID:	2ee2c4008393e3cc340f0fc8e833e3ad (1445391360972809133)

**Comment by samwzlim** [comment]
Same issue here on Win10 21H1 Insider Program Beta Channel. Tried installing the Insider version over at https://zvirtualdesktop.com/ but was unable to open as well. @mzomparelli just a heads up!

**Comment by mzomparelli** [comment]
I just tested on the insider build last night.

Thanks for this info though. I'm going to look into the "System.NotSupportedException" error this evening.

**Comment by mzomparelli** [comment]
Are you using an old insider build?
This is the version from your error message:
OS Version: 10.0.19043.2.0.0.256.48

Here is the version I'm running:
Version 10.0.21313.1000

The best I can do is ensure it works on the most recent builds. Based on the version you are running it would probably work with the 20H2 version of zVD however zVD probably is forcing you to update because your version is higher than the latest build.

What I'm saying is, your version of insider doesn't contain the changes Microsoft made to the VD interfaces thus zVD crashes because zVD tries to consume the interface with the changes.

**Comment by mzomparelli** [comment]
Knowing that 19043 does not contain the changes I could rebuild the zVD 20H2 build to include 19043 and it should be fine. Let's try that.

**Comment by mzomparelli** [comment]
ok, I just updated. Please try and download the **20H2** version from https://zvirtualdesktop.com/

**Comment by samwzlim** [comment]
It works! Cheers :)
