### ISSUE TITLE
Page Down key is missing

### ISSUE THREAD

**Issue by navix** [mzomparelli/zVirtualDesktop#37]
There are two Page Up keys instead:
![screen](https://nvx.me/screens/2017-04-11_09-43-45_d6y98.png)

**Comment by mzomparelli** [comment]
Thanks for pointing this out. I'm not sure how this would have happened, but I will investigate tonight.

**Comment by mzomparelli** [comment]
For some stupid reason the Next and Prior keys are used for PageUp and PageDown respectively.
I made the box sort now and I will continue to think about how I can make this easier for all of you. I've also changed it so that it reads the enum names instead of values. Some of them have the same value which is why it grabs the first and duplicates it. I changed that to get the enum names, but I'm not sure how that will pan out. You can use Next and Prior for your hotkeys. You don't need an update.

https://msdn.microsoft.com/en-us/library/system.windows.forms.keys(v=vs.110).aspx

**Comment by mzomparelli** [comment]
After digging deeper, it goes like this. If you want PageDown then use next. If you want PageUp then use PageUp. WTF. You will need an update so you don't see duplicates. Keep a lookout for version 1.0.28 tonight. 1.0.27 should prompt you to update when you open and an update is available.

**Comment by mzomparelli** [comment]
I've made some changes here to make it easier to get the key you want. I'm going to try and handle another issue or two before I publish, but there will definitely be an update tonight. Unfortunately, these settings are now not compatible. I could have handled migrating the setting, but I'm too lazy for that right. It's not difficult to setup settings again. I know it's still an inconvenience so I'm sorry.

**Comment by navix** [comment]
Thanks a lot, it works fine now.
