### ISSUE TITLE
Repo cluttered?

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#42]
Hi, I tried to to download zVD from the main download button, but all I got was a 4k empty ZIP.
The latest available version I found in the repo was 1.0.22
So I installed that and upon first time launch, it tells me the 1.040 is available, but that just points back to the same empty 4k ZIP.
In one of your previous posts, I found a link to 1.0.30, so I installed that instead and it has the round-robin feature, which I like a lot.
But 1.0.40 is nowhere to be found, and 1.0.30 is not in the repo, but the link works.

Oh, and I must say - I failed to understand the purpose of the checkbox for the windows keys, but I chose to check it (not knowing why).  :-)
Anyway - everything is getting better and better!

**Comment by hansek** [comment]
I'm confirming this issue, it's look like there is an issue in the IIS server configuration.

**Comment by mzomparelli** [comment]
Confirmed - I'm looking at my server now to figure out what is happening.

**Comment by mzomparelli** [comment]
[zVirtualDesktop.zip](https://github.com/mzomparelli/zVirtualDesktop/files/947294/zVirtualDesktop.zip)

I've added the zip here so you guys can use 1.0.40 while I fix this issue.

**Comment by mzomparelli** [comment]
The link should now work from the main page. Let me know if you still have issues.

**Comment by oywino** [comment]
Nope, the main page link is still not working for me. All I get is an empty (4k) ZIP-file.
But your direct link works.

**Comment by mzomparelli** [comment]
thanks, I am investigating.

**Comment by mzomparelli** [comment]
Looks like my zip was corrupt. I fixed that. Let me know if it's still broken.

**Comment by oywino** [comment]
Also (for what it is worth), my AVG Antivirus system now reprots zVD v1.0.40 as malware, named IDP.Generic

**Comment by mzomparelli** [comment]
yeah, I noticed that too. You can view the source with .NET decompiler which will show you my actual source since I am not obfuscating. I'm not doing anything malicious and I'm investigating why some version compiled trigger a detection while some don't. One thing I can think of is that I'm not signing my app. Anyway, thanks for pointing this out. I will continue to look into this.

Another thing that caused the virus detection was with one version I used a packer to make the exe smaller. Virus tend to do this as well so it was triggered as a virus even though it is not. I'll mess with this tonight and hopefully I can stop that detection. Let me know if newer versions continue to get detected as a virus.

**Comment by mzomparelli** [comment]
Free .NET Decompiler

https://www.jetbrains.com/decompiler/download/download-thanks.html?platform=windowsWeb

**Comment by mzomparelli** [comment]
I see that I failed to answer your question about the checkbox. This overrides CTRL+WIN+LEFT or RIGHT. It still moves you to a different desktop, but the default Windows implementation does not loop back around when you are on the last desktop. This feature has been called "Round Robin". Let me know if you need more explanation.

EDIT:

I realize you are referring to a checkbox that was on the Hotkey form. This is no longer an option since all of them override by default. Since it is default now, that checkbox is no longer on the form.
