### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by enumag** [mzomparelli/zVirtualDesktop#44]
I downloaded the latest zVirtualDesktop (1.0.22) from https://github.com/mzomparelli/zVirtualDesktop/releases. When I start the application it pops a message that a new version 1.0.40 is available. Which is odd as such version is not here on GitHub. When I try to download the 1.0.40 version the downloaded file is not a valid zip, just a html file with some error.

**Comment by mzomparelli** [comment]
[zVirtualDesktop.zip](https://github.com/mzomparelli/zVirtualDesktop/files/947330/zVirtualDesktop.zip)

Use this link while I fix my server issues. This link is version 1.0.40, the current version.

**Comment by enumag** [comment]
Alright, thanks.

**Comment by mzomparelli** [comment]
My zip was corrupt on the server. The main link should work now. Let me know if you have issues with the main link.

**Comment by mzomparelli** [comment]
I stopped doing releases on GitHub so that's why the release only goes up to version 1.0.22. The app checks for and downloads an update automatically now...that is, when everything is working properly. I do this because I'm still making changes and want every user to have the best possible experience.
