### ISSUE TITLE
Altdesk-like navigation bar for the desktops

### ISSUE THREAD

**Issue by enumag** [mzomparelli/zVirtualDesktop#46]
In my opinion the best software for virtual desktops is [Altdesk](http://www.astonshell.com/altdesk/). Unfortunately it is now a bit outdated but I'm still considering using it on Win 10 as well. Here is a screenshot how I was using it previously on Windows 7:

![altdesk](https://cloud.githubusercontent.com/assets/539462/25282804/dcab532c-26b1-11e7-9c25-63808c56d85b.png)

The benefits of this interface are:
- I always know what programs I have running at the moment and which desktop they're running on.
- With a single click I can switch to any program on any desktop.
- I can drag&drop any program to any desktop easily.

Of course this would be a lot of work and I don't know if it would be popular. My friends like it when I show it to them but they get discouraged when I tell then the truth that Altdesk sometimes disappears under the taskbar with no easy way to get it back.

Just close this issue if you don't like the idea.

**Comment by mzomparelli** [comment]
Thanks for the feedback. I will look into program you mention and see what I can implement to make you a happy user of zVirtualDesktop. All comments are welcome here and I try to do what I can to make features that make my users happy.

**Comment by ghost** [comment]
A similar feature that has a smaller profile on the taskbar is the taskbar pager in dexpot. This program is replacing dexpot for me, so that feature would be amazing! Here's a picture:
![image](https://www.classe.cornell.edu/~seb/celestia/images/dexpottbpager.jpg)

**Comment by enumag** [comment]
@amrahman96 What made you abandon Dexpot?

In case of Altdesk it's not really part of a taskbar, it can be anywhere. And it's actually bad because the taskbar is imho the best position and Altdesk sometimes disappered behind it.

**Comment by ghost** [comment]
Dexpot's developer, while still active on the forums, has not seemed to make any progress on the Win10 update for a couple years now. There are several bugs in win 10, such as crashing windows if I set it to run on startup (by any means), "ghost" windows for metro apps randomly appearing in the taskbar pager, and programs from other desktops randomly showing up on every desktops taskbar and alt+tab menu while still being treated like they are only on the original desktop. This program uses the native implementation of multiple desktops, so it's both less resource intensive and less error prone, and the developer seems to be very actively updating it. It also has most of the features I used in dexpot.

**Comment by mzomparelli** [comment]
I would just like to point out that for me, I'm trying to reduce what is on the taskbar. I usually know which desktop I put something on and I don't need any indicators that tell me what's on which desktop. If I do need that then I use the "Task View" view that Microsoft implemented.

As I think about how I would implement the feature you guys are talking about, one way was to mimic the Task View, but display every desktop as a column and only show the Icons/Caption for the windows instead of a preview. Then you would be able to drag and drop from that view. Basically, it would be an overlay like Task View. This was just one thought I've had. Feedback on that thought would be appreciated.

**Comment by ghost** [comment]
I think that's a pretty good idea. It might be nicer to do rows instead of columns, just so that you don't have to move the mouse as far, but otherwise I think that would pretty much satisfy my needs.

**Comment by mzomparelli** [comment]
ok, I'll head down that path then. I personally would prefer columns (in my head it makes more sense), but because of your feedback I feel it makes sense to allow the user to decide rows or columns.

**Comment by mzomparelli** [comment]
A little taste of what I'm working on. Feedback is welcome as always.

![image](https://cloud.githubusercontent.com/assets/10564234/25417156/b4080326-2a07-11e7-9f19-dad26da9c2de.png)

**Comment by ghost** [comment]
A lot of my windows that I put on different desktops are chrome windows with the same title, since they are from different classes that use the same site (which irritatingly names tabs all the same). I was thinking you could do something like below, so that we could still see a nice preview of the window, and mousing over an icon would make that preview the big featured one. Not sure how easy this would be to implement though.
![mockup](http://i.imgur.com/iS5IJSE.jpg)

**Comment by mzomparelli** [comment]
Thanks for the feedback. I will look into this.

**Comment by mzomparelli** [comment]
I do like the way that program does it, but I want to try by columns first. I'm imagining the screen filled like the task view, but more like the image below. You'll get scroll bars if needed, but when full screen I could probably fit about 7 in each column. The column might have multiple columns in it depending how my desktops you have. I will evenly distribute the columns to fit the screen. Two desktops means half the screen for desktop 1 windows and the other half for desktop 2 windows. I created space to put a thumbnail preview of the window in. I don't want to copy the idea from Alt-Desk. I want to try a different way. This resembles Trello for me. Many people like Trello.

![image](https://cloud.githubusercontent.com/assets/10564234/25508105/9dd8c97c-2b75-11e7-8216-7829f1b0c423.png)

**Comment by mzomparelli** [comment]
I just read your post again and realized you mocked that up in Photoshop. I thought you had a screenshot from AltDesk. Anyway, I feel like to move windows in your mockup I would have to hover over the desktop row to see the windows then I could grab a window and drag to another desktop. Is that what you were thinking? That's not bad idea. I'm envisioning all windows on the screen at all times so it would be quicker moving windows around.

**Comment by ghost** [comment]
That was pretty much my idea, but you would move things around by moving the icon squares up/down rows. Mousing over a row would show the windows on that desktop and mousing over a specific icon would make that window's preview the big one, but you wouldn't have to actually grab the window preview to move it, you would just use the icon.
With the previews, I do think that the column setup could also be good. I am worried that the previews would be too small though. I use [The Great Suspender](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg?hl=en), so a lot of my windows look the same _and_ have the same title, so unless I can read the other tabs in the preview, the preview won't help me (I know, my situation is annoying, but people don't set good website titles).
This is roughly what it would look like on my desktop (1920x1080):
![image](http://i.imgur.com/5nXwq2L.jpg)
As you can see, the previews aren't super helpful. Maybe if you made it so that hovering over a window for ~100 milliseconds would show a larger preview, like this?
![image](http://i.imgur.com/fpBMFN9.jpg)
Here I can read the tabs, so I can tell which desktop it belongs to.


Another random idea: If you put your mouse over a window and type a number, the window will get sent to that desktop. This way you wouldn't have to move your mouse back and forth a bunch.

**Comment by mzomparelli** [comment]
I'm making progress, but I've run into issues that are slowing me down while I try and figure out a solution.

Dragging and dropping between containers is proving to be difficult so this view is just a form with no separate containers.

I have a lot of windows that I need to filter out. This has always been a problem in this app that none of you have seen. This view brings visibility to that issue which means I must figure out how to filter out certain windows.

The only thing preventing this from being functional is my inability to drag and drop between containers. What you see here is live previews from zVirtualDesktop and the thumbnails are movable and sizable.

![image](https://cloud.githubusercontent.com/assets/10564234/25551148/5962db58-2c46-11e7-98b9-66d9b6d61ea7.png)

**Comment by ghost** [comment]
Is the problem with metro apps? Dexpot has this same issue (as mentioned [here](http://dexpot.de/forum/viewtopic.php?f=12&t=6078&start=20)), and it seems to have something to do with metro apps being pre-loaded by superfetch.
Actualtools seems to have [fixed this problem](https://www.actualtools.com/virtualdesktops/whatsnew/) (Search for "metro", it's the first one you'll find) but I'm not sure how.

**Comment by mzomparelli** [comment]
As you can see from the screenshot in the previous post, yes, most of them are metro app. Thanks for the tip about superfetch. I'll look into it. That screenshot has a pile of thumbnails in the upper left corner that I just left there instead of spreading them out.

**Comment by mzomparelli** [comment]
It works!

![image](https://cloud.githubusercontent.com/assets/10564234/25553031/ae539b20-2c6e-11e7-9ba8-1419914b1bfa.png)

**Comment by mzomparelli** [comment]
You can try it out, but if you try and bring up the view after you have changed desktops then the program will hang. I'm still ironing out the bugs. To bring up the view just left click on the System Tray icon.

This is not stable and shouldn't be used as a normal version. Just for testing.

[zVirtualDesktop.zip](https://github.com/mzomparelli/zVirtualDesktop/files/966285/zVirtualDesktop.zip)

**Comment by mzomparelli** [comment]
I managed to filter out all those metro apps that aren't visible with one line of code to check the style.

`if ((GetWindowLongA(hWnd, GWL_STYLE) & TARGETWINDOW) != TARGETWINDOW)`

**Comment by mzomparelli** [comment]
I released version 1.0.41 that includes this. I'm going to give it a shot as rows like you suggested. I'm still looking for a way to filter these Metro windows.

**Comment by mzomparelli** [comment]
Soon I will release version 1.0.42 which makes the left most column the column for pinned windows. You can now pin and unpin simply by dragging into this column.

![image](https://cloud.githubusercontent.com/assets/10564234/25642835/ed2eec6e-2f61-11e7-8c65-cc204e1b484e.png)

**Comment by mzomparelli** [comment]
I like my Desktop View a lot. It's growing on me. I use it in place of alt+tab when I'm not flipping back and fourth between two windows.

I figured out how to close those metro app windows. Simply use desktop view and right click on the window. It will take you there and open the window. Close it after it loads and it will be gone.

I'm going to close this issue. Further feedback can be done in a new issue.

![image](https://cloud.githubusercontent.com/assets/10564234/25647493/109a7eea-2f88-11e7-93d8-b2c9e9acc539.png)

**Comment by mzomparelli** [comment]
@enumag @amrahman96 

Have you had a chance to use Desktop View? What's your opinion? I like it, but I know you both had different ideas which makes your feedback meaningful.

**Comment by ghost** [comment]
I like it for the most part. My main complaint I have to move all the way up to a window to switch to that desktop, and there is no way to switch to an empty desktop. What makes intuitive sense to me is that if you left click anywhere in a column without dragging, you would be taken to that desktop (and I like how it currently  works where if you click on an a window, that window is brought to the foreground), and right clicking anywhere would cancel switching.

Another small complaint is that I keep thinking the "pinned" column is desktop 1. What if the pinned section was a row at the bottom that went across the whole screen? I also think that makes more intuitive sense in terms of showing that these windows span all desktops.

Another complaint, also pretty small, is just the amount of time it takes to generate the previews every time I open task view. I have a fairly large amount of windows open, and it's a little annoying having to wait every time. Maybe if you cached the previews to a temp folder and only updated the ones on the current desktop?

And finally, it would be nice if the previews filled the space a little more. They're pretty small, although for the most part it hasn't been a problem.

**Comment by ghost** [comment]
Also the large preview on hover feature I suggested would be really helpful.
As you can see, when I first open chrome and have to move windows across desktops, it's pretty hard to tell what's what without a larger preview.
![image](https://i.imgur.com/Yh4Fr0A.png)

**Comment by mzomparelli** [comment]
@amrahman96 thanks for the feedback.When I release version 1.0.49 you will be able to click the label headers in Desktop View to go to that desktop. last night I thought about switching like you say so that when you left click in a desktop column it will take you to that desktop. Look forward to seeing that.

I like your idea about putting the pinned windows along thew bottom. I too was getting confused about Desktop 1.

I'll see what I can do to make the previews load faster and the mouse hover to enlarge the preview.

**Comment by mzomparelli** [comment]
@amrahman96 I very much like your idea of putting the pinned windows in a row on the bottom. It's a little more involved than I thought it would be so I'm creating a new issue specifically for this.

**Comment by mzomparelli** [comment]
@amrahman96 
The thumbnail size is auto-sized based on the column width. The height is then calculated to maintain the aspect ratio of your display.

I see you don't have that many windows open. How long is it taking to populate that screen shot you provided? I've had more windows open and it takes less than a second. My laptop is a pretty crappy i5 with integrated graphics.

**Comment by ghost** [comment]
It takes about a full second with that many windows, and about three seconds if my laptop is unplugged. I have an i7-6700HQ (and other generally good specs) so it should be pretty snappy.

**Comment by mzomparelli** [comment]
Background processes can interfere. That I have noticed. Any ideas aside from increasing the priority of the process?

 I can't cache because these are live thumbnails. I'll check again to see what I can speed up.
