### ISSUE TITLE
zVD identified as Virus

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#50]
Hi, 
tonight zVD was killed, blocked and quarantined by AVG while running ! 
I assume as a result of an update of the AVG antivirus database.
My attempt to relaunch zVD resulted in aggressive attacks from AVG even though I tried to cancel the attack. Finally, Windows itself is now flashing a big blue "You cannot run this program on this computer" message across my screen.
I'm stuck.

**Comment by mzomparelli** [comment]
I too had it bring up Smartscreen. You should be able to get passed that. As far as anti-virus. I'm sorry it's doing that, but I promise it will do nothing malicious if you add it to you exceptions in AVG. I am looking into this.

The odd thing is some trigger virus detection and some builds don't. I just scanned with virus total and it's very odd what it's triggering. This could be the result of my new feature that gets thumbnails for every window. I'll dig into this to see if it's the problem.

I don't use Anti-Virus and rely on Virus Total only. So nothing is blocking the app from running for me.

**Comment by mzomparelli** [comment]
The blue screen you see is probably smartscreen filter and you should be able to get past that. I'm at work now, but I will check this out this evening.

**Comment by mzomparelli** [comment]
I submitted v1.0.41 to AVG describing what this app does and why I think it's being flagged. If I want to solve this for good then I need to sign app, but getting a cert can be expensive.

https://secure.avg.com/submit-sample

**Comment by mzomparelli** [comment]
One thing you could check is if the file is blocked by Windows. Right-click the file and click Properties. On the General tab look toward the bottom for a checkbox that says Unblock. Windows sometimes blocks EXEs that came from the internet. Especially when unzipped and the updater downloads the unzipped version from my site. If you got the exe from my site or the app updated itself (in which case came from my site) then I guarantee a good exe. I cannot make that guarantee if you download from another location. My site and possibly a github comment that I post are the only place I would guarantee a good program.

**Comment by mzomparelli** [comment]
This is also the reason that I took the code down. This app could easily be modified to log keys without the user even knowing it. By limiting the forks and download locations I can help the user be safe from running a modified version of this app.

**Comment by mzomparelli** [comment]
I should point as well that I am not using any third party libraries. The code for which I didn't write comes from Grabacr07's Virtual Desktop API for which I use the code directly and not a compiled library. This means that I have access to all the code that is being compiled and I'm compiling with Visual Studio 2017. I'm not infected by a virus that could be injecting itself into my newly compiled app. So with that said, I am 100% confident that there is no malicious activity happening in this app. In case you had any doubts, I hope this helps clear your concerns.

https://github.com/Grabacr07/VirtualDesktop

**Comment by mzomparelli** [comment]
AVG is not showing as a virus through Virus Total.
https://www.virustotal.com/en/file/b408e10429cad565c8417fd125ecae5b90a4ab97003c47850777bab815fd3944/analysis/1493641868/

Nonetheless, I'm going to figure why these are being triggered and what I can do about it.

**Comment by mzomparelli** [comment]
I tested if it was my updating method which works like below:
1. Get the latest version number from my SQL Server running @ zomp.co - it does this through a web-service - c'mon, I'm not stupid enough to store credentials to my SQL server in any app.
2. If the version of the app is not equal to the value returned from the server then...
3. zVirtualDesktop extracts a downloader exe that I built (so I know it's not malicious) and then executes it and shuts itself down.
4. The downloader simply downloads a file from zomp.co/Files.aspx?id=zVD which is the latest version of zVirtualDesktop
5. Once the download is complete the downloader app starts the newly downloaded zVirtualDesktop.exe and then shuts itself down. You can see this in task manager and the update is visible. It goes by the name zVirtualDesktopUpdater.exe. 

I removed all of this code and the embedded Downloader exe and sent it to virus total. Without the downloader it still screams virus.

I do this for the convenience of you guys and myself. I got bored of copying the new exe into my startup folder. Seems irrelevant anyway since it does not appear to be the cause of the false positive.

The only other thing I can think of is the keyboard hook. I don't know if this makes sense though since the keyboard hook was implemented way back in like version 1.0.10. This is the heart of the program. I could go back to registering hotkeys via Win32, but that significantly decreases the number of hotkeys you can choose from. I personally wouldn't find it useful then and since I'm the one developing this app I'm keeping the keyboard hook. 

Even if I wanted to make a virus. I certainly wouldn't put it on GitHub attached to my account with my real name :)

I'll send each new version to the bigger Anti-Virus companies to get my app white-listed. That might be the only thing I can do, but I will continue to look into this.

**Comment by mzomparelli** [comment]
I changed the update process to ask before downloading.

**Comment by mzomparelli** [comment]
AVG confirmed that version 1.0.41 does not trigger false positive with their software. Here is the email from them. Maybe you can provide what is being asked for in the email.


Hello,
Thank you for contacting AVG.
Please accept our apologies for all the inconvenience caused. Unfortunately the provided file doesn't seem to be detected by AVG.
We will be glad to analyze the issue but before that we need to analyze your threat detection by AVG. Could you please send us a screenshot of the detection message you're getting?
?1. Attach the screenshot of virus database version of AVG:
•	AVG 2016 > Open AVG > Options > About AVG
•	AVG 2017 > Open AVG > Menu > About
2. Attach the screenshot of the detection of the file as threat by AVG. To create screenshot, please follow the instructions in the below link. 
 Create a screenshot.
We will analyze the received files and provide you with further information. When you respond to this email please do not change the email subject. This will help us reply to you without delay. 
Thank you for your co-operation.
Best regards,

Miroslav Rotrekl
AVG Customer Care

**Comment by mzomparelli** [comment]
I'm leaving this issue open because zVirtualDesktop is being detected by some and I am continuing to deal with it by sending my app to be white listed. I encourage everyone to reply to this thread with any info they might be seeing from their anti-virus.

Once again, I would like to point out that I maintain all the code and my dev PC is not infected. These are false positives. I know it can be scary executing an app that some anti-virus are showing as a virus. I would be very concerned myself. My only intention is to make zVirtualDesktop to the best of my ability so that I can provide you guys with the best experience that I can deliver.

**Comment by mzomparelli** [comment]
Version 1.0.42 appears to only trigger a false positive for one low end detector. I will continue to monitor each build.

**Comment by mzomparelli** [comment]
zVirtualDesktop is no longer being detected as a virus.

One thing that I believe helped this was adding the prompt to download the update instead of just updating it. I can see how that would look bad, but I still think prompt-less, fully automated updates are the way to go. I will leave the prompt though.
