### ISSUE TITLE
Question for all users

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#60]
What do you think of the GUI? Both the Desktop View and the settings form?

The reason I ask is that I created this in WinForms and I think I did a good job with the GUI. I am considering starting a version 2 in WPF. What do you guys think?

**Comment by Aran-Fey** [comment]
In my opinion, the UI doesn't make a great first impression. I'm not sure how to put this, but it looks kind of... minimalist, in a bad way. It looks very flat; for example the "tabs" in the settings dialog look like a bunch of text labels, not like an actual "tab widget".

Don't get me wrong though, the GUI is quite alright the way it is. All the functionality is there, and you get used to its somewhat unusual look quickly. It's really just the first impression that's a bit lacking.

Similarly, the Desktop View was quite... overwhelming the first time I opened it. I opened it accidentally by clicking the icon in the taskbar, so it was quite a shock when it suddenly opened a gigantic fullscreen window (because you wouldn't usually expect taskbar icons to open large windows like that). I only had 2 desktops at the time, so this massive full screen dialog looked like overkill.
I'm used to it now after a few hours of using the app though. It's pretty nice once you familiarize yourself with it.

**Comment by mzomparelli** [comment]
@Rawing thanks for the feedback! It is supposed to be minimalist. The UI isn't really the showcase.

You might have noticed that there are no external libraries for this exe. That is by design and you are right that the settings UI is labels. I think it looks pretty good, but I will try and make it look more appealing.

Your feedback is greatly appreciated. I listen to my users and try to accommodate them the best that can.

**Comment by mzomparelli** [comment]
@Rawing Despite my unappealing GUI, would you agree that this program blows away any of the Auto HotKeys ones? The reason I made this program was because that was all i can find and I wanted something that was an all-in-one package with zero installation. I'm also trying to prevent having external DLL libraries which is partly why it's so plain. If I want it to look nicer then I have to create my own controls. The thumbnail controls in Desktop View are an example of a simple custom control.

**Comment by Aran-Fey** [comment]
I've never used any Autohotkey programs, so I can't comment on that.
I don't think making a more stylish GUI needs to be a high priority task for you though. After the initial "huh, this interface looks unusual" moment you hardly even notice the differences anymore. I don't think the interface is so bad that it scares off potential new users or makes interaction with the program difficult.

**Comment by ghost** [comment]
The GUI looks fine. One default change that I wanted to make right away was to add a hotkey to show the desktops GUI; in the current program that action is called "Show Desktop View". I think that perhaps it should be mapped to Win + Tab by default (overriding the default windows view); at the very least I feel it should be mapped to something because it's worth pressing. I had to search the keyboard mapping menu to find that option.

I think the section of the GUI for "pinned to all desktops" is intuitive and an improvement over the current Windows GUI; in the Windows desktops GUI, you can't see which windows or apps are pinned except by right-clicking their windows; that seems like a small fail for Windows.

**Comment by mzomparelli** [comment]
@noido thanks for the feedback!

I had thought about using Alt+Tab for Desktop View, but that particular hotkey does not override very well. I was having an issue preventing it from still doing the default Alt+Tab function. I have Desktop View mapped to CTRL+SHIFT+Z and I really like it. I find that easier to press than Alt+Tab. To each their own I guess. I'll see what I can do about overriding Alt+Tab and if successful I will create a default hotkey for this. I don't want to create a static hotkeys though. All of them should be configurable and thus if I default this to Alt+Tab it would only create it for new users or users that reset their settings. If I can't override Alt+Tab properly, what is another good hotkey that Desktop View should default to?

**Comment by mzomparelli** [comment]
Sorry, I meant Win+Tab in my above comment
