### ISSUE TITLE
Request: Rearranging virtual desktops windows

### ISSUE THREAD

**Issue by aaronweewee** [mzomparelli/zVirtualDesktop#71]
Heyy I really like what your doing with this, do you think it is possible to find a way to "rearrange" the desktops? :')

**Comment by mzomparelli** [comment]
So basically, you want to move all windows from one desktop to another all at once? This could be done, but this would be low priority for me since it doesn't seem like a valuable feature and my backlog is getting long. Maybe you can explain it better that will want me to increase the priority.

**Comment by aaronweewee** [comment]
I've mapped out my mouse side buttons to move to the next and previous desktop it is super efficient way to maneuver about desktops. But when i have 8-9 desktop open, its really difficult to jump from desktop 2 to 8.

eg. if "Work Desktop" is desktop 2 and i create "Data Desktop" that is at desktop 8, I'll have to shift all my excel sheets to desktop 3. vice versa

I guess that's why we have the hot keys to help us jump quickly. its really easy if its the first 3-4 desktops and i use it a lot as well. But it becomes a finger stretching exercise when i have to flip between desktop 2 and 8 with one hand. 

Using the round robin feature is actually a miracle life saver as so far in this regard, but it would be super neat feature if we could re order the desktop. :)

**Comment by mzomparelli** [comment]
Thanks for describing your intention in more detail. Have you tried Desktop View? It will allow you to easily and quickly jump to any window on any desktop. You could assign a mouse button to open Desktop View. Then you could navigate your desktops without needing the keyboard. Ever since I've added Desktop View I haven't used the hotkeys. Not the ones for navigating anyway.

What if you had a hot key to move all windows from current desktop to another desktop? That's the equivalent to rearranging the desktops.

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Re-arrange Desktops](https://trello.com/c/QWEUGrlD/2-re-arrange-desktops)

**Comment by mzomparelli** [comment]
I have a need for this feature now so I'm going to figure something out soon.

**Comment by mzomparelli** [comment]
I have some ideas for this and the conversation will be continued in the following issue.

https://github.com/mzomparelli/zVirtualDesktop/issues/143
