### ISSUE TITLE
Update fails and no way to disable update notification

### ISSUE THREAD

**Issue by darboleda** [mzomparelli/zVirtualDesktop#76]
Auto-update doesn't work for me, so I'd like to have an option to turn it off and update on my own time instead of it bothering me every few hours.

**Comment by mzomparelli** [comment]
I want everyone to have the latest updates so that unnecessary bug issues aren't created. This ensures that even if the EXE is shared outside of GitHub that the end user is aware of an updated version.

If I changed it to only prompt on startup would that be acceptable for you?

I hope to fix this issue with the updater in the very near future.

**Comment by darboleda** [comment]
Yes that would be acceptable, too. It's just annoying that the popup appears and interrupts things even though at the moment it's useless. It doesn't help that there have been several updates over the last few days. Another (longer-term) suggestion would be to use a tray notification message for available updates instead. This will give us some OS level control over it at least.

**Comment by mzomparelli** [comment]
Version 1.0.56 will only check for updates on launch. I should be publishing that update soon. I look into the notifications suggestion.
