### ISSUE TITLE
Replace Built-in TaskView Launcher Icon with zVD Icon

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#78]
I want zVD to have the option of replacing the TaskView Icon or at least being able to put zVD icon (the desktop indicator) next to the Start Menu.

I've done some research on this and I've come up empty handed. If anyone can point me in the right direction please feel free to do that here. I'll continue to update this as I progress.

**Comment by oywino** [comment]
For what it's worth, I have turned off the TaskView icon since I began using zVD.
I see no reason to bring it back. It's just another icon wasting valuable space, while offering little value. After all, when I miss it, I can always hit Win+Tab.
My advice - spend your valuable time, expertise and energy on other issues. :-)

**Comment by mzomparelli** [comment]
Thanks for reading this!!

That's my point too. I stopped using TaskView as well. I think my icon in it's place would be better. Imagine TaskView icon giving you a number that indicates which desktop you are on. Basically moving my icon from the system tray to the where TaskView is.

I'm not actually putting any time into this. I looked and there appears to be no way to do this, so I put it here as a reminder to myself and so others can help out if they choose to do so.

Is there a particular area in zVD that you think I need to spend more time on? I'm thinking DesktopView needs some more work.
