### ISSUE TITLE
zVD using 40% CPU

### ISSUE THREAD

**Issue by Aran-Fey** [mzomparelli/zVirtualDesktop#79]
I just upgraded to version 1.0.58 from 1.0.56, and now zVD permanently uses 35-40% CPU power. I'm not even interacting with it, all I do is start it.

Is there any way I can downgrade to an older version until this is fixed?

**Comment by mzomparelli** [comment]
I'm taking a look now. I should be able to apply an update to fix this.

**Comment by mzomparelli** [comment]
@Rawing I have addressed this in an update. It should be ok now while I figure out a better solution.

Version 1.0.59 - Restart zVD and it should ask you to update.

I'm going to leave this open while I come up with a better solution.

As far as downgrading...I don't want my users to do this because then they are discouraged from updating further. Instead, I want my users to know that I address bugs quickly and updating is a good thing.

**Comment by oywino** [comment]
I too experienced this issue when upgrading to 1.0.58
But from what I saw, zVD consumed 100% of a single logical core (randomly shifting around between my 8 cores). On average, this amounted to approx 20% total constant CPU load.  Upgrading to 1.0.59 seem to have solved this issue for now.

**Comment by mzomparelli** [comment]
@oywino thanks for the update. I'm happy to know that 1.0.59 fixed this for you. It's not a bad fix, but it's not the way that I want to handle it because there are potential side effects. Definitely create a new issue if something doesn't feel right. I use zVD every single day, can't live without it now, so I too will be looking for anything that doesn't feel right. Thanks @Rawing for pointing this out in the first place. It's people like you guys that make zVD better. Never hesitate to tell me how you feel about something. All feedback is greatly appreciated.

**Comment by mzomparelli** [comment]
There is a slightly tweaked version of 1.0.59 that I just put out. You won't see it unless you manually update.

https://zomp.co/files.aspx?id=zvd

**Comment by oywino** [comment]
What are we supposed to look for?

**Comment by mzomparelli** [comment]
You shouldn't notice much difference if any at all.

**Comment by mzomparelli** [comment]
Closing this as resolved
