### ISSUE TITLE
Mouse goes crazy/laggy after updating 1.0.61

### ISSUE THREAD

**Issue by jjhidalgar** [mzomparelli/zVirtualDesktop#81]
I recently updated to this version using auto-updater. I found out that my mouse is not working properly when app is running, it is completely lagged. Any ideas?

**Comment by mzomparelli** [comment]
Did you use version 1.0.57, 1.0.58, 1.0.59, or 1.0.60? The mouse hook was implemented in 1.0.57. 

When did you do the update to 1.0.61?

Can you try the latest? There were some slight changes done to 1.0.61. The check for updates could cause the program to freeze when a connection to my server could not be obtained. The changes made those calls on a separate thread to avoid blocking the program.

Download the latest here (this is a tweaked version of 1.0.61):
https://zomp.co/files.aspx?id=zvd

**Comment by jjhidalgar** [comment]
Fixed. Somehow this time I downloaded from realeases 1.0.51 and then inmediatly updated to 1.0.61 and that path took me to the bug I was telling. Downloading 1.0.61 directly from your link works good.

Edit. Not sure if i am right or wrong. I found slightly wrong mouse behaviour (might me how I feel it now, need more testing)

**Comment by mzomparelli** [comment]
Even if the main program froze, the mouse hook is on a separate thread so it shouldn't be causing any issues. Definitely keep me posted if you experience anything unusual. I will be testing myself and I'll report my findings in this issue.

**Comment by jjhidalgar** [comment]
I tested it further and I am sure it is lagging my mouse. It even makes it annoying.

If you like me to share any info about my pc/hw I will be happy to supply.

**Comment by mzomparelli** [comment]
Yes, please comment with the spec of your machine. Is the lagging persistent or just at certain times? I think I will add a button that can toggle the mouse hook on and off. This would let you turn it off, but would break any mouse hotkeys you created.

**Comment by mzomparelli** [comment]
Will you please download a modified version of 1.0.61 and replace your existing copy? I added a button Settings -> About -> Start/Stop Mouse Hook.

This will let you turn it off while I investigate it. When off, any hotkeys that use the mouse will not work.

https://zomp.co/files.aspx?id=zvd

**Comment by mzomparelli** [comment]
I've been able to reproduce this issue using Excel and a VLOOKUP formula. Changing Excel setting so that it uses one less than the number of cores in my processor fixed it for me. This occurs when a processor intensive task is allowed to execute (and hog) the processing power.

I've tried several other things too. I set the mousehook thread priority to `highest`
I've tried setting zVD process to real-time.

The only thing that works is disallowing a processor intensive process from hogging all cores.

I'm looking for a better solution. I would like to know if it's a specific program that may be hogging your processing poser.

Until I find a solution, I suggest stopping the mouse hook altogether, stopping when you need to perform a heavy task, or limiting that heavy task to leave a spare core.

**Comment by mzomparelli** [comment]
Here's something I'm considering...

Make the mouse hotkeys require a modifier key. The mousehook is only enabled when there is a modifier key pressed. This means that if you see a mouse lag then you could simply release the modifier key.

**Comment by mzomparelli** [comment]
In the next version...

If you turn off mouse hook it will still be enabled when you press a modifier key. Once keys are up it will turn off the mouse hook. This will limit your mouse hotkeys for use only with modifers. The only one I can think of to use without modifiers is the TASKBAR-SCROLL which I currently use for volume up and down.

You can use this now if you download from here.

https://zomp.co/files.aspx?id=zvd

**Comment by jjhidalgar** [comment]
Nice. Thanks for your time and efforts. Your last version works perfect on me since I do not use mouse hooks so I simply did not enable them. 

Anyway I find it kind of weird that enabling them makes the mouse lag. I would love to help but my experience with c# is below zero. But it seems very weird taking into account that we are not even following the mouse path but just wheel or buttons. So I can't stop thinking that there must be a solution since other apps do not cause such an issue.

Currently I have sharex and discord opened. As well as gogole drive, odrive, google music and scptoolkit.
My cpu is a i5 6600K, 16GB, and a AMD R9 390. In case you need this data to think of something. Anyway I would start looking if there is other way to make some low-level hooks in c# that won't make this problem. Though your idea of only enabling them on modifier is very clever and may even be enough.

By the way I have recently discovered your app. I setup only the "show desktop view" shortcut on my mouse and it seems that I will have this one app installed forever.

**Comment by mzomparelli** [comment]
It makes me happy that you like DesktopView. It's also my favorite part of the app and I have it setup to a mouse key. Since this new feature resolves your issue I'm going to close this.

**Comment by mzomparelli** [comment]
I should point out that other apps using a mouse hook could experience the same thing. Typically a game will and I suspect C++ might run faster without the overhead of the .Net Framework. I have searched for solutions, but I haven't found anything. I can't use RawInput because I need to be able to prevent the keys from going to the next hook when a hotkey is activated. RawInput runs asynchronously thus I can't prevent keys from getting though. I'll keep thinking about it, but I think having it only activate with a modifier key should suffice for those having issues with it always on.
