### ISSUE TITLE
Create Chocolatey Package

### ISSUE THREAD

**Issue by Marcus-L** [mzomparelli/zVirtualDesktop#96]
To make it easier to install, create a package on chocolatey to allow users to install the tool from the command line. Good idea? I could help with this.

**Comment by Marcus-L** [comment]
Nevermind, just noticed this is a closed-source project.

**Comment by mzomparelli** [comment]
@Marcus-L what can be easier than a single EXE file?

**Comment by Marcus-L** [comment]
I think you mean, "what could be easier than this 17 step process?"

1. open browser
2. search google for the name of the program
3. click through a few links until you find the github page
4. scan through the page until you find the download link
5. click the download link
6. open the zip file in 7zip or windows explorer
7. run the exe from the zip
8. realize it's not an installer, and that it's running from the temp directory it was extracted to
9. exit the program
10. drag the exe to the desktop
11. decide to move it to c:\program files
12. accept UAT prompt to create the folder in program files and move the exe
13. start the exe
14. google "start menu folder location"
15. open start menu folder
16. create shortcut from exe to start menu programs folder
17. delete the downloaded zip from Downloads folder
Done.

vs, open powershell:
```powershell
choco install zvirtualdesktop
```
Done.

Here's a few helpful links:
[Why Chocolatey?](https://github.com/chocolatey/choco/wiki/Why)
[Why Boxstarter?](http://boxstarter.org/WhyBoxstarter) (for making windows install scripts)
[Example Boxstarter script](https://gist.github.com/jessfraz/7c319b046daa101a4aaef937a20ff41f) for someone's Windows box

**Comment by mzomparelli** [comment]
So instead of using well known utilities that basic users understand, you'd rather they use a terminal window and execute text commands?

The tool you are showing me is not for single installations. It's a IT tool for deployment. Normal people don't want to execute text commands in a terminal window.

open browser - **Already open, I'm a regular website viewer.**
search google for the name of the program - **this is another thing that users do on a regular basis - use a search engine**
click through a few links until you find the github page - **I would hope that if you know the name of the app that you have a link to the GitHub page. If not, then I would question the person or website informing you about this app**
scan through the page until you find the download link - **no link to the zVD page is an issue with how you were informed**
click the download link - **normal people would rather click a button over executing a text command in a terminal window.**
open the zip file in 7zip or windows explorer - **this is a pretty standard thing when downloading stuff**
run the exe from the zip - **No comment**
realize it's not an installer, and that it's running from the temp directory it was extracted to - **My page says that it runs as a single EXE and no installation. You shouldn't run EXE unless you have read up on what it is. Shame on the user for executing without reading.**
exit the program
drag the exe to the desktop
decide to move it to c:\program files - **I would not run the app from this folder.**
accept UAT prompt to create the folder in program files and move the exe
start the exe
google "start menu folder location" - **in my page I tell you how to get the the startup folder. Simply type Startup into the address  bar of a File Explorer window.**
open start menu folder
create shortcut from exe to start menu programs folder - **It states on my page that the EXE should be in the Startup folder, not a shortcut.**
delete the downloaded zip from Downloads folder - **this is up to the user**



I see your point with all of this, but it's all pretty basic stuff unlike executing commands in a terminal.

You made this into a lot of steps.  Follow the directions on the page and it's only a few steps.

IMHO, I would rather have a single EXE over an installation any day.

Nonetheless, you have proven to me that even the simplest things can be difficult for some users so I will see what i can do to make it easier.

**Comment by Marcus-L** [comment]
Trust me, once you start using chocolatey you will change your mind. Why not give it a try?

Anyway, a bit of a moot point. Have you any plans to open source this project at some time in the future? I forked the project from the last open source commit, and might start hacking on it from that point. Would have been much nicer to contribute to the actual project but of course it is up to you whether to allow that.

**Comment by mzomparelli** [comment]
Thanks for the tip. I'll check it out.

I had plans to open source, but I'm not sure I want to anymore. My main reason being that it's too easy to turn this into a keylogger. Most of my users don't care about code and would probably execute any program that provides similar features. Someone could fork it, make it malicious, and distribute it as zVD. By running a version downloaded from my server you can be sure the app is free of malicious intent.

I don't think the version you forked (my last code commit) utilizes a keyboard hook. I think it still uses WinAPI to register hotkeys. My current code utilizes a mouse hook and a keyboard hook. Those are the things needed for a keylogger and that's the reason I'm not open sourcing.

A few other reasons for not open sourcing...

I like donations :)
The code needs better organization and I've been lazy about cleaning it up and don't want to burden someone else to cleanup my mess.

**Comment by mzomparelli** [comment]
If you have some ideas for features then let me know. It seems as though you have something in mind and I'd love to hear about it.

As long it's not about deployment ;), it's already easy to write a power shell script to download and extract it somewhere.

**Comment by giggio** [comment]
+1 for using Chocolatey. It is how I install everything.

**Comment by mzomparelli** [comment]
ok, I'll reopen this and see what i can do.

**Comment by jan-glx** [comment]
Please excuse this unrelated comment, everyone. @mzomparelli your arguments 2&3 are valid but selfish [I suspect the underlying reason for argument 3 to be that you don't want to be ashamed nor have someone do it better]. This is totally fine, almost everything in our world is driven by selfish motives (I think even most FOSS contributions are). However, your main argument is invalid: In the current situation still anybody could come and package your .exe with e.g. https://github.com/TheFox/keylogger and redistribute it (sure, illegally but it was illegal anyway). Also, not everyone needs to be able to check if your code does something malicious, it needs just one who points it out; And right now this one person would have hard time to do so. 

Come to the bright side, we don't have cookies but ... _please disable your ad-blocker to read the rest of this post._

**Comment by fluffynuts** [comment]
I, for one, would be interested in learning from your code, if it were open-sourced. I (feebly) attempted something like what you've done ages ago, and I'd love to learn what you learned to get it right (because I very obviously didn't). Indeed, I only learned of this project because of the discussions I've had with a friend over my failed attempts -- he recently pointed me here, and I'm really enjoying using zDesktop.

Open-sourcing would also allow other people to tackle issues, contributing back to the project. I've found that contributions to my projects from other people have proven invaluable -- just my 2c.

Also, to add an obtuse counter-argument: a malicious user could create a "clone" of your project which doesn't even have virtual desktop functionality -- it just needs to be a rootkit in an installer that looks like yours. The best solutions I can think of are:
1) have an official download location (which you do, but I have some suggestions) -- make sure that all users know that they should only download it from there. Some suggestions:
a) I see that you have valid ssl at https://zomp.co/ -- but I'd suggest enforcing ssl connections
b) have an official, easy-to-recognise landing page for zVirtualDesktop, with download links. Refer people to this page from your project README. This would make it easier for users to recognise the "correct" place to download the software. Sure, someone can clone your site, but every little bit counts, right?
2) sign your releases. Hash them too and encourage users to test the hashes in case of compromised installers (MITM attacks and such -- especially for people behind corporate firewalls where the company believes that they have the right to spy on SSL traffic and hide their crappy activities via root certificate installation)
3) Get the app to update itself, using these mechanisms (download over ssl, verify certificates, checksum the download, etc) -- users may not test hashes, but your app can.
4) Warn users of the dangers of having a non-verified install: it didn't even occur to me that your app could be modified to be a keylogger!
5) Open-source it! More eyes are better! If your app does some really low-level hooks, the last thing you want is there to be some easily-exploitable vulnerability in the app -- and whilst there might be someone who could notice such a flaw and exploit it, there are plenty of people who, upon noticing, would report it and try to assist in resolving it.

**Comment by mzomparelli** [comment]
@jan-glx you are right. There is some selfishness involved here. You are also correct that a keylogger can be injected into zVD and distributed.  I'm going to make some changes to help my users test for a safe app by using suggestions by fluffynuts.

@fluffynuts, your suggestions are very good and I plan to implement some of them. Specifically, a formal landing page that describes zVD and shows the hash values for every release so that it can be compared to the version downloaded. I will also perform the hash check upon downloading an update to ensure there was not MITM attack.

Would it be frowned upon if I agreed to publish the code when I reach a certain goal? Let's say 2,000 GitHub stars or $1,000 in donations? This is not to say I would not publish the source sooner without reaching a goal if I decide to.
Having a popular GitHub repository looks great on a resume.

**Comment by fluffynuts** [comment]
"frowned upon"? I don't know. It's ultimately your project, your code. You can always do with it what you please. It seems a little strange to have something not open-source on a public repo on GitHub, but there's no law (or even etiquette, that I know of) against it.
Would I like to see open-sourcing sooner rather than later? Sure, but perhaps that's just my own selfishness. You need to decide the point at which (if ever) you want to completely open the code.

**Comment by mzomparelli** [comment]
For the record, it's here on GitHub because it started out as open source. Code for that project is still available if you reverse the commits where I deleted everything. It just doesn't include DesktopView and the enhanced method of handling hotkeys. There are several forked versions that have done the work of reversing the deletion commit so you can check that out if you want an idea of how I implemented zVD.

**Comment by Marcus-L** [comment]
Thanks for re-opening this issue @mzomparelli. Everyone else -- discussion here is getting off-topic from the packaging issue, I suggest moving further discussion about the source code and rootkit/security to a different issue.

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Chocolaty Package](https://trello.com/c/xSZ7hwXy/22-create-chocolaty-package)

**Comment by mzomparelli** [comment]
I installed Chocolatey and looking into create a zVD package. I've read some tutorials, but I'm still confused.   Does anyone have any advice for me? Maybe someone knows the script I need to create the Chocolatey package! @Marcus-L  I would love to have your help.

EDIT: I've cleaned up some of the comments. I wanted to retain some of them, but I don't know if they can be moved. The comments didn't belong in this issue, sorry, but they were still good comments.

**Comment by nicolasdejong** [comment]
I prefer Scoop actually: https://github.com/lukesampson/scoop/wiki/Chocolatey-Comparison

And I'd like the project to be open-source as well. Perhaps I then can do a fix or improvement myself through merge requests (even though I'm a Java/js dev only, can't be much different eh?). Then again, this does add some social stress because people might not just suggest a change or new feature, they'll do the work as well and if you then don't like the change or addition, you have to say 'no' anyway... And you should!

**Comment by mzomparelli** [comment]
I've requested zVD chocolatey package and it is in need of a maintainer. I can be the maintainer of the chocolatey package if someone can walk me through what to do. I also give permission to anyone to maintain this package for us. The download link for zVD is always the same so I suspect this should be fairly easy to setup and maintain. 

https://github.com/chocolatey/chocolatey-package-requests/issues/178

@nicolasdejong  I will look into Scoop

**Comment by mzomparelli** [comment]
A chocolatey package has been created. Thanks @chtof

https://chocolatey.org/packages/zvirtualdesktop
