### ISSUE TITLE
Network Allow Connection?

### ISSUE THREAD

**Issue by gitty8** [mzomparelli/zVirtualDesktop#97]
To which IP i should allow connection? Can explain each connection?
https://i.imgur.com/jq1mYuy.png

http://ip-lookup.net/index.php?ip=73.209.134.9 (http://zomp.co/Files.aspx?id=... )
http://ip-lookup.net/index.php?ip=91.198.22.70 (checkip-ams.dyndns.com )
http://ip-lookup.net/index.php?ip=216.146.38.70 (http://checkip.dyndns.org) 

`details
Pattern match: "http://tempuri.org/IService/UploadFileT"
Pattern match: "http://tempuri.org/IService/UploadFileResponse"
Pattern match: "http://tempuri.org/IService/GetNextEmailCommandT"
Pattern match: "tempuri.org/IService/GetNextEmailCommandResponse"
Pattern match: "http://tempuri.org/IService/AddEventToDatabaseT"
Pattern match: "tempuri.org/IService/AddEventToDatabaseResponseo"
Pattern match: "http://tempuri.org/IService/SendEmailT"
Pattern match: "http://tempuri.org/IService/SendEmailResponse"
Pattern match: "http://tempuri.org/IService/zVD_CurrentVersionT"
Pattern match: "tempuri.org/IService/zVD_CurrentVersionResponsew"
Pattern match: "http://tempuri.org/IService/zVD_GetDonorsT"
Pattern match: "tempuri.org/IService/zVD_GetDonorsResponsey"
Pattern match: "http://tempuri.org/IService/zVD_GetMessageT"
Pattern match: "tempuri.org/IService/zVD_GetMessageResponse"
Pattern match: "http://schemas.datacontract.org/2004/07/zomp.co_WebService\"
Pattern match: "http://schemas.datacontract.org/2004/07/zomp.co_WebService"
Pattern match: "tempuri.org/IService/zVD_CurrentVersionResponsey"
Pattern match: "tempuri.org/IService/zVD_GetMessageResponse@"
Pattern match: "https://zomp.co/z/ZompWebService.svc"
Pattern match: "https://www.google.com"
Pattern match: "https://www.paypal.me/MichaelZomparelli/"
Pattern match: "https://zomp.co/Files.aspx?id=zVDEXE1"
Pattern match: "http://checkip.dyndns.org/"
Pattern match: "https://github.com/mzomparelli/zVirtualDesktop"
Pattern match: "https://github.com/mzomparelli/zVirtualDesktop/issues/new"
Pattern match: "https://www.paypal.me/MichaelZomparelli/5"
Pattern match: "https://www.paypal.me/MichaelZomparelli/10"
Pattern match: "https://www.paypal.me/MichaelZomparelli/25"
Pattern match: "https://www.paypal.me/MichaelZomparelli/200000"
Pattern match: "https://zomp.co/Files.aspx?id=zVDEXE1\"`

**Comment by mzomparelli** [comment]
73.209.134.9 is where updates come from. It's my personal server. Certain exceptions are logged here too so that the program can be improved for everyone.  This is the only connection that needs to be enabled to receive updates.

216.146.38.70 is a service I use so I can get your IP address for the purpose of geolocation. I am using this info to determine where I should start with additional languages. I can and will do away with this since I can determine this from my server when you download the app.

91.198.22.70 appears to be my server's old IP address which is now 73.209.134.9. This IP can change at any time which is why I use a domain name (zomp.co).

You don't need to allow any of these connections for the app to be functional. You just won't get updates and you won't be able to see who has donated. You can still get updates by downloading a new EXE manually.

As far as my SQL Server goes, only I have access and the firewall blocks every incoming connection unless on the very short list of white-listed IPs. The reason your PC can talk to my SQL Server is because it goes through my web service. If you were to try and connect to my SQL Sever it would look like it's non-existent.
